### ISSUE TITLE
example@neko2.net doesn't be blocked

### ISSUE THREAD

**Issue by saito-kosuke** [boywithkeyboard-archive/is-disposable#3]
your blacklist has neko2.net
but example@neko2.net doesn't be blocked

**Comment by saito-kosuke** [comment]
the snag has been fixed

**Comment by boywithkeyboard** [comment]
@saito-kosuke, this package is **not** meant to be complete as we only use a single public blacklist as source.

If you want something more complete, I'd suggest to signup for the waitlist of my upcoming cloud service [devyl](https://devyl.net), which will offer a managed API with an astonishing list of 200,000+ domains.

**Comment by saito-kosuke** [comment]
@boywithkeyboard Thank you for your reply. Understood.
